/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_concurrente;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jsoup.Jsoup;

/**
 *
 * @author jose9
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    CardLayout bodyCardLayout;
    String email = "usuario@correo.com";
    DefaultTableModel tablaAlertas;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    String panelRetornoFiltros;
    /**
     * Creates new form InferfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        tablaAlertas = (DefaultTableModel) this.tblAlertas.getModel();
        this.setLocationRelativeTo(null);
        this.bodyCardLayout = (CardLayout)(this.Body.getLayout());
        PanicBot.setBackground(new Color(0,0,0,0));
        Maps1.setBackground(new Color(0,0,0,0));
        Alertas1.setBackground(new Color(0,0,0,0));      
        jButton6.setBackground(new Color(0,0,0,0));  
        jButton1.setBackground(new Color(0,0,0,0));  
        jButton7.setBackground(new Color(0,0,0,0));  
        jButton2.setBackground(new Color(0,0,0,0));  
        btnAgregarAlerta.setBackground(new Color(0,0,0,0));  
        jButton20.setBackground(new Color(0,0,0,0));  
        jButton21.setBackground(new Color(0,0,0,0));
        jButton22.setBackground(new Color(0,0,0,0));
        jButton23.setBackground(new Color(0,0,0,0));
        jButton24.setBackground(new Color(0,0,0,0));
        jButton25.setBackground(new Color(0,0,0,0));
        jButton26.setBackground(new Color(0,0,0,0));
        jButton27.setBackground(new Color(0,0,0,0));
 
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Principal = new javax.swing.JPanel();
        PanicBot = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Alertas1 = new javax.swing.JButton();
        Maps1 = new javax.swing.JButton();
        Start_BG = new javax.swing.JLabel();
        Altertas = new javax.swing.JPanel();
        cbTiposAlertas = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlertas = new javax.swing.JTable();
        btnAgregarAlerta = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Mapa = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        Filtros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jButton5 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        PanelOpciones = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        ContactosAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbNombreContacto = new javax.swing.JTextField();
        tbApellidosContactos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbTelefonoContacto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tbEmailContacto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnAgregarContacto = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        Perfil = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        CambiarContraseña = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        AgregarAlerta = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        ContactosModificar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 667));
        setMinimumSize(new java.awt.Dimension(375, 667));
        setResizable(false);
        setSize(new java.awt.Dimension(375, 667));

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setPreferredSize(new java.awt.Dimension(375, 667));

        PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_PanicBoton_Normal.png"))); // NOI18N
        PanicBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanicBotActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Settings.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Alertas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Alerta.png"))); // NOI18N
        Alertas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alertas1ActionPerformed(evt);
            }
        });

        Maps1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Mapa.png"))); // NOI18N
        Maps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Maps1ActionPerformed(evt);
            }
        });

        Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Normal_Blue-01.jpg"))); // NOI18N

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PanicBot, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Alertas1)
                .addGap(7, 7, 7)
                .addComponent(Maps1))
            .addComponent(Start_BG)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(PanicBot, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alertas1)
                    .addComponent(Maps1)))
            .addComponent(Start_BG, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Body.add(Principal, "Principal");

        Altertas.setBackground(new java.awt.Color(255, 255, 255));
        Altertas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbTiposAlertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agresion", "Asalto", "Hurto", "Vandalismo", "Otro" }));
        Altertas.add(cbTiposAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 180, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Settings.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Altertas.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 50, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Altertas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, -1));

        tblAlertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Lugar", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tblAlertas);

        Altertas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 342, 370));

        btnAgregarAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alerta_Agregar.png"))); // NOI18N
        btnAgregarAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlertaActionPerformed(evt);
            }
        });
        Altertas.add(btnAgregarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 180, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alertas_BG-01.jpg"))); // NOI18N
        Altertas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Altertas, "Alertas");

        jPanel7.setBackground(new java.awt.Color(0, 153, 102));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton20)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton20)
                .addContainerGap(585, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MapaLayout = new javax.swing.GroupLayout(Mapa);
        Mapa.setLayout(MapaLayout);
        MapaLayout.setHorizontalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MapaLayout.setVerticalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Body.add(Mapa, "Mapa");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButton5.setText("Aplicar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FiltrosLayout = new javax.swing.GroupLayout(Filtros);
        Filtros.setLayout(FiltrosLayout);
        FiltrosLayout.setHorizontalGroup(
            FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiltrosLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FiltrosLayout.createSequentialGroup()
                        .addComponent(jButton21)
                        .addGap(9, 9, 9)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FiltrosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        FiltrosLayout.setVerticalGroup(
            FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton21)
                .addGap(83, 83, 83)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        Body.add(Filtros, "Filtros");

        PanelOpciones.setBackground(new java.awt.Color(255, 255, 255));

        jButton12.setText("Perfil de Usuario");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setText("Contactos de emergencia");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Opciones");

        jButton17.setText("Modificar contraseña");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOpcionesLayout = new javax.swing.GroupLayout(PanelOpciones);
        PanelOpciones.setLayout(PanelOpcionesLayout);
        PanelOpcionesLayout.setHorizontalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton22)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        PanelOpcionesLayout.setVerticalGroup(
            PanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton22)
                .addGap(84, 84, 84)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        Body.add(PanelOpciones, "PanelOpciones");

        ContactosAgregar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Telefono");

        jLabel4.setText("Email");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Telefono", "Email"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        btnAgregarContacto.setText("Agregar");
        btnAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContactoActionPerformed(evt);
            }
        });

        jButton9.setText("Modificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Eliminar");

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContactosAgregarLayout = new javax.swing.GroupLayout(ContactosAgregar);
        ContactosAgregar.setLayout(ContactosAgregarLayout);
        ContactosAgregarLayout.setHorizontalGroup(
            ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactosAgregarLayout.createSequentialGroup()
                .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactosAgregarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContactosAgregarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tbApellidosContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(ContactosAgregarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarContacto)
                            .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbEmailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tbTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(ContactosAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactosAgregarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addGap(22, 22, 22))
                    .addGroup(ContactosAgregarLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(ContactosAgregarLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton23)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ContactosAgregarLayout.setVerticalGroup(
            ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactosAgregarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton23)
                .addGap(32, 32, 32)
                .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbApellidosContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbEmailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAgregarContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContactosAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(28, 28, 28))
        );

        Body.add(ContactosAgregar, "ContactosAgregar");

        Perfil.setBackground(new java.awt.Color(255, 255, 255));
        Perfil.setAutoscrolls(true);

        jLabel10.setText("Telefono");

        jLabel11.setText("Nombre");

        jLabel12.setText("Apellidos");

        jLabel9.setText("Email");

        jTextField12.setEditable(false);

        jLabel13.setText("Genero");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino", "Otro" }));

        jLabel14.setText("Fecha de nacimiento");

        jTextField13.setEditable(false);

        jButton16.setText("Guardar Cambios");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PerfilLayout = new javax.swing.GroupLayout(Perfil);
        Perfil.setLayout(PerfilLayout);
        PerfilLayout.setHorizontalGroup(
            PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PerfilLayout.createSequentialGroup()
                .addGroup(PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PerfilLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jTextField12)
                            .addGroup(PerfilLayout.createSequentialGroup()
                                .addGroup(PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField9)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField13)
                            .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(PerfilLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton25)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PerfilLayout.setVerticalGroup(
            PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PerfilLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton16)
                .addGap(96, 96, 96))
        );

        Body.add(Perfil, "Perfil");

        CambiarContraseña.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Contraseña Actual");

        jLabel16.setText("Nueva contraseña");

        jLabel17.setText("Confirme nueva contraseña");

        jButton18.setText("Guardar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CambiarContraseñaLayout = new javax.swing.GroupLayout(CambiarContraseña);
        CambiarContraseña.setLayout(CambiarContraseñaLayout);
        CambiarContraseñaLayout.setHorizontalGroup(
            CambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiarContraseñaLayout.createSequentialGroup()
                .addGroup(CambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CambiarContraseñaLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton26))
                    .addGroup(CambiarContraseñaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(CambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jTextField14)
                            .addComponent(jTextField15)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CambiarContraseñaLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        CambiarContraseñaLayout.setVerticalGroup(
            CambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CambiarContraseñaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton26)
                .addGap(73, 73, 73)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton18)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        Body.add(CambiarContraseña, "CambiarContraseña");

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarAlertaLayout = new javax.swing.GroupLayout(AgregarAlerta);
        AgregarAlerta.setLayout(AgregarAlertaLayout);
        AgregarAlertaLayout.setHorizontalGroup(
            AgregarAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlertaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton27)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        AgregarAlertaLayout.setVerticalGroup(
            AgregarAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlertaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton27)
                .addContainerGap(573, Short.MAX_VALUE))
        );

        Body.add(AgregarAlerta, "AgregarAlerta");

        ContactosModificar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellidos");

        jLabel7.setText("Telefono");

        jLabel8.setText("Email");

        jButton11.setText("Guardar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContactosModificarLayout = new javax.swing.GroupLayout(ContactosModificar);
        ContactosModificar.setLayout(ContactosModificarLayout);
        ContactosModificarLayout.setHorizontalGroup(
            ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactosModificarLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactosModificarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11)
                    .addGroup(ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addGroup(ContactosModificarLayout.createSequentialGroup()
                            .addGroup(ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jTextField7)
                        .addComponent(jTextField8)))
                .addGap(21, 21, 21))
        );
        ContactosModificarLayout.setVerticalGroup(
            ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactosModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton24)
                .addGap(52, 52, 52)
                .addGroup(ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContactosModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(jButton11)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        Body.add(ContactosModificar, "ContactosModificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.bodyCardLayout.show(this.Body, "Perfil");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.bodyCardLayout.show(this.Body, "ContactosAgregar");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.bodyCardLayout.show(this.Body, "CambiarContraseña");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.bodyCardLayout.show(this.Body, "ContactosModificar");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.bodyCardLayout.show(this.Body,"PanelOpciones");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Alertas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alertas1ActionPerformed
        this.refrescarTablaAlertas();
        this.bodyCardLayout.show(this.Body,"Alertas");
    }//GEN-LAST:event_Alertas1ActionPerformed

    private void Maps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Maps1ActionPerformed
        this.bodyCardLayout.show(this.Body,"Mapa");
    }//GEN-LAST:event_Maps1ActionPerformed

    private void PanicBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanicBotActionPerformed
        if(PanicBot.isSelected()){   
            PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonPanico_Rojo.png")));
            Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Alert_Red-01.jpg")));
            
            Gson gson = new Gson();
            ClienteTCP client = new ClienteTCP();
            HashMap usuario = new HashMap();
            
            usuario.put("email",email);
            usuario.put("accion","emergencia");  
            String payload = gson.toJson(usuario);
            String resultado = client.enviaServidor(payload);
            JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
            boolean exito =  jsonObject.get("exito").getAsBoolean();

            if (exito){
                JOptionPane.showMessageDialog(null, "Se han enviado alertas a sus contactos de emergencia");
            } else {
                JOptionPane.showMessageDialog(null, "No se ha encontrado ningun contacto de emergencia");
            }

        } else {
           PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_PanicBoton_Normal.png")));
           Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Normal_Blue-01.jpg"))); 
        }
            
    }//GEN-LAST:event_PanicBotActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       this.bodyCardLayout.show(this.Body,"PanelOpciones");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAgregarAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlertaActionPerformed
//        this.bodyCardLayout.show(this.Body,"AgregarAlerta");
        String tipoAlerta = this.cbTiposAlertas.getSelectedItem().toString();
        Gson gson = new Gson();
        ClienteTCP client = new ClienteTCP();
        HashMap usuario = new HashMap();

        usuario.put("tipoAlerta",tipoAlerta);
        usuario.put("accion","crear alerta");  
        usuario.put("email",email);
        String payload = gson.toJson(usuario);
        String resultado = client.enviaServidor(payload);
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        boolean exito =  jsonObject.get("exito").getAsBoolean();
//        this.refrescarTablaAlertas();
        if (exito){
            JOptionPane.showMessageDialog(null, "Se ha enviado la alerta al servidor.");
            Date fecha = Calendar.getInstance().getTime();
            
            String [] row = {fecha.toString(),"San Jose",tipoAlerta};
            tablaAlertas.addRow(row);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha enviado la alerta al servidor.");
        }        
        
    }//GEN-LAST:event_btnAgregarAlertaActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton27ActionPerformed

    private void btnAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContactoActionPerformed
        if(tbNombreContacto.getText().isEmpty() || tbApellidosContactos.getText().isEmpty() || tbTelefonoContacto.getText().isEmpty() || tbEmailContacto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
        HashMap usuario = new HashMap();
        ClienteTCP client = new ClienteTCP();
        Gson gson = new Gson();
        
        usuario.put("accion","crear contacto de emergencia");
        usuario.put("id",email);
        usuario.put("email",tbEmailContacto.getText());
        usuario.put("nombre",tbNombreContacto.getText());
        usuario.put("apellidos",tbApellidosContactos.getText());
        usuario.put("celular",tbTelefonoContacto.getText());
        
        String payload = gson.toJson(usuario);
        client.enviaServidor(payload);
        }
        
    }//GEN-LAST:event_btnAgregarContactoActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         if(jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty() || jTextField8.getText().isEmpty() || jTextField7.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
             
             
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if(jTextField15.getText().isEmpty() || jTextField16.getText().isEmpty() || jTextField14.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
            if(jTextField15.getText().equals(jTextField16.getText())){
                 JOptionPane.showMessageDialog(null, "Se cambio la contraseña");
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseña no son iguales");
            }
            
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() || jTextField11.getText().isEmpty() || jTextField13.getText().isEmpty() || jTextField12.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
        
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private JsonArray extraerAlertas(){
        Gson gson = new Gson(); //Objeto gson para serializar String a formato Json
        ClienteTCP client = new ClienteTCP(); //Cliente TCP para enviar datos
        HashMap reporte = new HashMap(); //Hashmap para enviar parametros al servidor
        JsonArray output = null; //Crea objeto nuevo de tipo JsonArray para poder acceder a cada evento individualmente
        
        //Agrega parametros
        reporte.put("accion","mis alertas");  
        reporte.put("email",email);
        
        String payload = gson.toJson(reporte);//Serializa parametros en formato JSON
        String resultado = client.enviaServidor(payload); //Agrega el mensaje devuelto por el servidor a un string

        //Se deserializa el string para extraer los eventos
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        String stringTemporal = jsonObject.get("reporte").getAsString();
//        System.out.println(prueba);

        if (!stringTemporal.equals("")){
        jsonObject = new JsonParser().parse(stringTemporal).getAsJsonObject();
        stringTemporal = jsonObject.get("eventos").getAsString();
    //        System.out.println(prueba);
        output = new JsonParser().parse(stringTemporal).getAsJsonArray();
    //        System.out.println(aux.toString());        
        }
        return output;
    }
    
    private void refrescarTablaAlertas(){
        JsonArray aux = this.extraerAlertas();
        JsonObject jsonObject;
        //Se itera en cada item del array para agregar una linea nueva a la tabla
        if (aux!=null){
            tablaAlertas.setNumRows(0);
            for (int i = 0; i < aux.size(); i++) {
                jsonObject = aux.get(i).getAsJsonObject();
                //Se extraen elementos especificos y se agregan a un array string
                String fecha = jsonObject.get("fecha").getAsString();
                String tipo = jsonObject.get("tipoAlerta").getAsString();
                String lugar = jsonObject.get("barrio").getAsString();
                String [] row = {fecha.toString(),lugar,tipo};
                tablaAlertas.addRow(row);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarAlerta;
    private javax.swing.JButton Alertas1;
    private javax.swing.JPanel Altertas;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel CambiarContraseña;
    private javax.swing.JPanel ContactosAgregar;
    private javax.swing.JPanel ContactosModificar;
    private javax.swing.JPanel Filtros;
    private javax.swing.JPanel Mapa;
    private javax.swing.JButton Maps1;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JToggleButton PanicBot;
    private javax.swing.JPanel Perfil;
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel Start_BG;
    private javax.swing.JButton btnAgregarAlerta;
    private javax.swing.JButton btnAgregarContacto;
    private javax.swing.JComboBox<String> cbTiposAlertas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField tbApellidosContactos;
    private javax.swing.JTextField tbEmailContacto;
    private javax.swing.JTextField tbNombreContacto;
    private javax.swing.JTextField tbTelefonoContacto;
    private javax.swing.JTable tblAlertas;
    // End of variables declaration//GEN-END:variables
}
