/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_concurrente;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jsoup.Jsoup;

/**
 *
 * @author jose9
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    CardLayout bodyCardLayout;
    String email = "usuario@correo.com";
    DefaultTableModel tablaAlertas;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    String panelRetornoFiltros;
    /**
     * Creates new form InferfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        tablaAlertas = (DefaultTableModel) this.tblAlertas.getModel();
        this.setLocationRelativeTo(null);
        this.bodyCardLayout = (CardLayout)(this.Body.getLayout());
        PanicBot.setBackground(new Color(0,0,0,0));
        Maps1.setBackground(new Color(0,0,0,0));
        Alertas1.setBackground(new Color(0,0,0,0));      
        jButton6.setBackground(new Color(0,0,0,0));  
        jButton1.setBackground(new Color(0,0,0,0));  
        jButton7.setBackground(new Color(0,0,0,0));  
        jButton2.setBackground(new Color(0,0,0,0));  
        btnAgregarAlerta.setBackground(new Color(0,0,0,0));  
        jButton20.setBackground(new Color(0,0,0,0));  
        jButton21.setBackground(new Color(0,0,0,0));
        jButton22.setBackground(new Color(0,0,0,0));
        jButton23.setBackground(new Color(0,0,0,0));
        jButton24.setBackground(new Color(0,0,0,0));
        jButton25.setBackground(new Color(0,0,0,0));
        jButton26.setBackground(new Color(0,0,0,0));
        jButton27.setBackground(new Color(0,0,0,0));
        AlertasFiltro_Boton.setBackground(new Color(0,0,0,0));
        FiltroBack_Boton.setBackground(new Color(0,0,0,0));
        AjustesFiltroSave_Boton.setBackground(new Color(0,0,0,0));
        jButton12.setBackground(new Color(0,0,0,0));
        jButton14.setBackground(new Color(0,0,0,0));
        jButton15.setBackground(new Color(0,0,0,0));
        jButton17.setBackground(new Color(0,0,0,0));
        jButton16.setBackground(new Color(0,0,0,0));
        ModContactosSafe_Bot.setBackground(new Color(0,0,0,0));
        ChangePassSave_Boton.setBackground(new Color(0,0,0,0));
 
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Principal = new javax.swing.JPanel();
        Principal_mensaje_label = new javax.swing.JLabel();
        PanicBot = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Alertas1 = new javax.swing.JButton();
        Maps1 = new javax.swing.JButton();
        Start_BG = new javax.swing.JLabel();
        Altertas = new javax.swing.JPanel();
        AlertasFiltro_Boton = new javax.swing.JButton();
        cbTiposAlertas = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlertas = new javax.swing.JTable();
        btnAgregarAlerta = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Mapa = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        Filtros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        AjustesFiltroSave_Boton = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        FiltroBack_Boton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        PanelOpciones = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        BACKGOURND = new javax.swing.JLabel();
        ContactosAgregar = new javax.swing.JPanel();
        tbNombreContacto = new javax.swing.JTextField();
        tbApellidosContactos = new javax.swing.JTextField();
        tbTelefonoContacto = new javax.swing.JTextField();
        tbEmailContacto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnAgregarContacto = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Perfil = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        CambiarContraseña = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        ChangePassSave_Boton = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        AgregarAlerta = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        ContactosModificar = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        ModContactosSafe_Bot = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 667));
        setMinimumSize(new java.awt.Dimension(375, 667));
        setResizable(false);
        setSize(new java.awt.Dimension(375, 667));

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setPreferredSize(new java.awt.Dimension(375, 667));
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Principal_mensaje_label.setBackground(new java.awt.Color(204, 204, 204));
        Principal.add(Principal_mensaje_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 310, 30));

        PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_PanicBoton_Normal.png"))); // NOI18N
        PanicBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanicBotActionPerformed(evt);
            }
        });
        Principal.add(PanicBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 360, 470));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        Principal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Settings.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Principal.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 50, 40));

        Alertas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Alerta.png"))); // NOI18N
        Alertas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alertas1ActionPerformed(evt);
            }
        });
        Principal.add(Alertas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        Maps1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Mapa.png"))); // NOI18N
        Maps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Maps1ActionPerformed(evt);
            }
        });
        Principal.add(Maps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Normal_Blue-01.jpg"))); // NOI18N
        Principal.add(Start_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        Body.add(Principal, "Principal");

        Altertas.setBackground(new java.awt.Color(255, 255, 255));
        Altertas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlertasFiltro_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FiltroBoton.png"))); // NOI18N
        AlertasFiltro_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlertasFiltro_BotonActionPerformed(evt);
            }
        });
        Altertas.add(AlertasFiltro_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 50, -1));

        cbTiposAlertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agresion", "Asalto", "Hurto", "Vandalismo", "Otro" }));
        Altertas.add(cbTiposAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 180, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Settings.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Altertas.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 50, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Altertas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, -1));

        tblAlertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Lugar", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tblAlertas);

        Altertas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 342, 370));

        btnAgregarAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alerta_Agregar.png"))); // NOI18N
        btnAgregarAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlertaActionPerformed(evt);
            }
        });
        Altertas.add(btnAgregarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 180, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alertas_BG-01.jpg"))); // NOI18N
        Altertas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Altertas, "Alertas");

        jPanel7.setBackground(new java.awt.Color(0, 153, 102));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton20)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton20)
                .addContainerGap(585, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MapaLayout = new javax.swing.GroupLayout(Mapa);
        Mapa.setLayout(MapaLayout);
        MapaLayout.setHorizontalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MapaLayout.setVerticalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Body.add(Mapa, "Mapa");

        Filtros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        Filtros.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 165, 261, -1));
        Filtros.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 339, 261, -1));
        Filtros.add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 391, 261, -1));

        AjustesFiltroSave_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        AjustesFiltroSave_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjustesFiltroSave_BotonActionPerformed(evt);
            }
        });
        Filtros.add(AjustesFiltroSave_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 160, 47));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        Filtros.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        FiltroBack_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        FiltroBack_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroBack_BotonActionPerformed(evt);
            }
        });
        Filtros.add(FiltroBack_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 30, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alertas_BG-01.jpg"))); // NOI18N
        Filtros.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Filtros, "Filtros");

        PanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Perfil.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 176, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ContactosBoton.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OpcionesBoton.png"))); // NOI18N
        PanelOpciones.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 176, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EdotarPassword_Boton.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 176, -1));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        BACKGOURND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BG-01.jpg"))); // NOI18N
        PanelOpciones.add(BACKGOURND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(PanelOpciones, "PanelOpciones");

        ContactosAgregar.setBackground(new java.awt.Color(255, 255, 255));
        ContactosAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ContactosAgregar.add(tbNombreContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 152, 140, -1));
        ContactosAgregar.add(tbApellidosContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 152, 140, -1));
        ContactosAgregar.add(tbTelefonoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 230, 320, -1));
        ContactosAgregar.add(tbEmailContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 300, 320, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Telefono", "Email"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        ContactosAgregar.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 386, 330, 203));

        btnAgregarContacto.setText("Agregar");
        btnAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContactoActionPerformed(evt);
            }
        });
        ContactosAgregar.add(btnAgregarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 336, -1, -1));

        jButton9.setText("Modificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        ContactosAgregar.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 607, -1, -1));

        jButton10.setText("Eliminar");
        ContactosAgregar.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 607, -1, -1));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        ContactosAgregar.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AddContactBG-01.jpg"))); // NOI18N
        ContactosAgregar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(ContactosAgregar, "ContactosAgregar");

        Perfil.setBackground(new java.awt.Color(255, 255, 255));
        Perfil.setAutoscrolls(true);
        Perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Perfil.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, -1));
        Perfil.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));
        Perfil.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 290, -1));

        jTextField12.setEditable(false);
        Perfil.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 290, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Perfil.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        Perfil.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PerfIlBG-01.jpg"))); // NOI18N
        Perfil.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Perfil, "Perfil");

        CambiarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        CambiarContraseña.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CambiarContraseña.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 202, 280, -1));
        CambiarContraseña.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, -1));
        CambiarContraseña.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 280, -1));

        ChangePassSave_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        ChangePassSave_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassSave_BotonActionPerformed(evt);
            }
        });
        CambiarContraseña.add(ChangePassSave_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 160, -1));

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        CambiarContraseña.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChangePasBG-01.jpg"))); // NOI18N
        CambiarContraseña.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(CambiarContraseña, "CambiarContraseña");

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarAlertaLayout = new javax.swing.GroupLayout(AgregarAlerta);
        AgregarAlerta.setLayout(AgregarAlertaLayout);
        AgregarAlertaLayout.setHorizontalGroup(
            AgregarAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlertaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton27)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        AgregarAlertaLayout.setVerticalGroup(
            AgregarAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlertaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton27)
                .addContainerGap(573, Short.MAX_VALUE))
        );

        Body.add(AgregarAlerta, "AgregarAlerta");

        ContactosModificar.setBackground(new java.awt.Color(255, 255, 255));
        ContactosModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ContactosModificar.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 162, 310, -1));
        ContactosModificar.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 310, -1));
        ContactosModificar.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 310, -1));
        ContactosModificar.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 310, -1));

        ModContactosSafe_Bot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        ModContactosSafe_Bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModContactosSafe_BotActionPerformed(evt);
            }
        });
        ContactosModificar.add(ModContactosSafe_Bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        ContactosModificar.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 6, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModContacto-01.jpg"))); // NOI18N
        ContactosModificar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(ContactosModificar, "ContactosModificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.bodyCardLayout.show(this.Body, "Perfil");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.bodyCardLayout.show(this.Body, "ContactosAgregar");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.bodyCardLayout.show(this.Body, "CambiarContraseña");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.bodyCardLayout.show(this.Body, "ContactosModificar");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void AjustesFiltroSave_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjustesFiltroSave_BotonActionPerformed

    }//GEN-LAST:event_AjustesFiltroSave_BotonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.bodyCardLayout.show(this.Body,"PanelOpciones");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Alertas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alertas1ActionPerformed
        this.refrescarTablaAlertas();
        this.bodyCardLayout.show(this.Body,"Alertas");
    }//GEN-LAST:event_Alertas1ActionPerformed

    private void Maps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Maps1ActionPerformed
        this.bodyCardLayout.show(this.Body,"Mapa");
    }//GEN-LAST:event_Maps1ActionPerformed

    private void PanicBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanicBotActionPerformed
        if(PanicBot.isSelected()){   
            PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonPanico_Rojo.png")));
            Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Alert_Red-01.jpg")));
            
            Gson gson = new Gson();
            ClienteTCP client = new ClienteTCP();
            HashMap usuario = new HashMap();
            
            usuario.put("email",email);
            usuario.put("accion","emergencia");  
            String payload = gson.toJson(usuario);
            String resultado = client.enviaServidor(payload);
            JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
            boolean exito =  jsonObject.get("exito").getAsBoolean();

            if (exito){
               Principal_mensaje_label.setText("Se han enviado alertas a sus contactos de emergencia");
            } else {
                Principal_mensaje_label.setText("No se ha encontrado ningun contacto de emergencia");
            }

        } else {
           PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_PanicBoton_Normal.png")));
           Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Normal_Blue-01.jpg"))); 
           Principal_mensaje_label.setText("");
        }
            
    }//GEN-LAST:event_PanicBotActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       this.bodyCardLayout.show(this.Body,"PanelOpciones");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAgregarAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlertaActionPerformed
//        this.bodyCardLayout.show(this.Body,"AgregarAlerta");
        String tipoAlerta = this.cbTiposAlertas.getSelectedItem().toString();
        Gson gson = new Gson();
        ClienteTCP client = new ClienteTCP();
        HashMap usuario = new HashMap();

        usuario.put("tipoAlerta",tipoAlerta);
        usuario.put("accion","crear alerta");  
        usuario.put("email",email);
        String payload = gson.toJson(usuario);
        String resultado = client.enviaServidor(payload);
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        boolean exito =  jsonObject.get("exito").getAsBoolean();
//        this.refrescarTablaAlertas();
        if (exito){
            JOptionPane.showMessageDialog(null, "Se ha enviado la alerta al servidor.");
            Date fecha = Calendar.getInstance().getTime();
            
            String [] row = {fecha.toString(),"San Jose",tipoAlerta};
            tablaAlertas.addRow(row);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha enviado la alerta al servidor.");
        }        
        
    }//GEN-LAST:event_btnAgregarAlertaActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton27ActionPerformed

    private void btnAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContactoActionPerformed
        if(tbNombreContacto.getText().isEmpty() || tbApellidosContactos.getText().isEmpty() || tbTelefonoContacto.getText().isEmpty() || tbEmailContacto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
        HashMap usuario = new HashMap();
        ClienteTCP client = new ClienteTCP();
        Gson gson = new Gson();
        
        usuario.put("accion","crear contacto de emergencia");
        usuario.put("id",email);
        usuario.put("email",tbEmailContacto.getText());
        usuario.put("nombre",tbNombreContacto.getText());
        usuario.put("apellidos",tbApellidosContactos.getText());
        usuario.put("celular",tbTelefonoContacto.getText());
        
        String payload = gson.toJson(usuario);
        client.enviaServidor(payload);
        }
        
    }//GEN-LAST:event_btnAgregarContactoActionPerformed

    private void ModContactosSafe_BotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModContactosSafe_BotActionPerformed
         if(jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty() || jTextField8.getText().isEmpty() || jTextField7.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
             
             
        }
    }//GEN-LAST:event_ModContactosSafe_BotActionPerformed

    private void ChangePassSave_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassSave_BotonActionPerformed
        if(jTextField15.getText().isEmpty() || jTextField16.getText().isEmpty() || jTextField14.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
            if(jTextField15.getText().equals(jTextField16.getText())){
                 JOptionPane.showMessageDialog(null, "Se cambio la contraseña");
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseña no son iguales");
            }
            
        }
    }//GEN-LAST:event_ChangePassSave_BotonActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() || jTextField11.getText().isEmpty() || jTextField12.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
        
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void AlertasFiltro_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlertasFiltro_BotonActionPerformed
        this.bodyCardLayout.show(this.Body,"Filtros");
    }//GEN-LAST:event_AlertasFiltro_BotonActionPerformed

    private void FiltroBack_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroBack_BotonActionPerformed
        this.bodyCardLayout.show(this.Body, "Alertas");
    }//GEN-LAST:event_FiltroBack_BotonActionPerformed

    private JsonArray extraerAlertas(){
        Gson gson = new Gson(); //Objeto gson para serializar String a formato Json
        ClienteTCP client = new ClienteTCP(); //Cliente TCP para enviar datos
        HashMap reporte = new HashMap(); //Hashmap para enviar parametros al servidor
        JsonArray output = null; //Crea objeto nuevo de tipo JsonArray para poder acceder a cada evento individualmente
        
        //Agrega parametros
        reporte.put("accion","mis alertas");  
        reporte.put("email",email);
        
        String payload = gson.toJson(reporte);//Serializa parametros en formato JSON
        String resultado = client.enviaServidor(payload); //Agrega el mensaje devuelto por el servidor a un string

        //Se deserializa el string para extraer los eventos
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        String stringTemporal = jsonObject.get("reporte").getAsString();
//        System.out.println(prueba);

        if (!stringTemporal.equals("")){
        jsonObject = new JsonParser().parse(stringTemporal).getAsJsonObject();
        stringTemporal = jsonObject.get("eventos").getAsString();
    //        System.out.println(prueba);
        output = new JsonParser().parse(stringTemporal).getAsJsonArray();
    //        System.out.println(aux.toString());        
        }
        return output;
    }
    
    private void refrescarTablaAlertas(){
        JsonArray aux = this.extraerAlertas();
        JsonObject jsonObject;
        //Se itera en cada item del array para agregar una linea nueva a la tabla
        if (aux!=null){
            tablaAlertas.setNumRows(0);
            for (int i = 0; i < aux.size(); i++) {
                jsonObject = aux.get(i).getAsJsonObject();
                //Se extraen elementos especificos y se agregan a un array string
                String fecha = jsonObject.get("fecha").getAsString();
                String tipo = jsonObject.get("tipoAlerta").getAsString();
                String lugar = jsonObject.get("barrio").getAsString();
                String [] row = {fecha.toString(),lugar,tipo};
                tablaAlertas.addRow(row);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarAlerta;
    private javax.swing.JButton AjustesFiltroSave_Boton;
    private javax.swing.JButton Alertas1;
    private javax.swing.JButton AlertasFiltro_Boton;
    private javax.swing.JPanel Altertas;
    private javax.swing.JLabel BACKGOURND;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel CambiarContraseña;
    private javax.swing.JButton ChangePassSave_Boton;
    private javax.swing.JPanel ContactosAgregar;
    private javax.swing.JPanel ContactosModificar;
    private javax.swing.JButton FiltroBack_Boton;
    private javax.swing.JPanel Filtros;
    private javax.swing.JPanel Mapa;
    private javax.swing.JButton Maps1;
    private javax.swing.JButton ModContactosSafe_Bot;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JToggleButton PanicBot;
    private javax.swing.JPanel Perfil;
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel Principal_mensaje_label;
    private javax.swing.JLabel Start_BG;
    private javax.swing.JButton btnAgregarAlerta;
    private javax.swing.JButton btnAgregarContacto;
    private javax.swing.JComboBox<String> cbTiposAlertas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField tbApellidosContactos;
    private javax.swing.JTextField tbEmailContacto;
    private javax.swing.JTextField tbNombreContacto;
    private javax.swing.JTextField tbTelefonoContacto;
    private javax.swing.JTable tblAlertas;
    // End of variables declaration//GEN-END:variables
}
