/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_concurrente;

import com.google.gson.Gson;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.sun.glass.events.KeyEvent;

/**
 *
 * @author jose9
 */
public class InterfazRegistro extends javax.swing.JFrame {
    CardLayout cardLayout;
    static String email;

    public InterfazRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cardLayout = (CardLayout)(this.PanelPrincipal.getLayout());
        jLabel13.setBackground(new Color(0,0,0,0));
        jButton5.setBackground(new Color(0,0,0,0));
        btnIngresar.setBackground(new Color(0,0,0,0));
        jButton6.setBackground(new Color(0,0,0,0));
        jButton7.setBackground(new Color(0,0,0,0));
        jButton7.setBackground(new Color(0,0,0,0));
        jButton8.setBackground(new Color(0,0,0,0));
        ResetPasswrod_Back.setBackground(new Color(0,0,0,0));
        resetPassword.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Ingresar = new javax.swing.JPanel();
        tbEmailIngreso = new javax.swing.JTextField();
        tbContraseñaIngreso = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        RecuperarContraseña = new javax.swing.JPanel();
        tbCorreoRecuperarContraseña = new javax.swing.JTextField();
        resetPassword = new javax.swing.JButton();
        ResetPasswrod_Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Registrar1 = new javax.swing.JPanel();
        correo = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        apellido = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        confirmarPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Registrar2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 667));
        setMinimumSize(new java.awt.Dimension(375, 667));
        setPreferredSize(new java.awt.Dimension(375, 667));
        setResizable(false);
        setSize(new java.awt.Dimension(375, 667));

        PanelPrincipal.setLayout(new java.awt.CardLayout());

        tbEmailIngreso.setBackground(new java.awt.Color(255, 255, 255));
        tbEmailIngreso.setForeground(new java.awt.Color(51, 0, 102));
        tbEmailIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbEmailIngresoKeyTyped(evt);
            }
        });

        tbContraseñaIngreso.setBackground(new java.awt.Color(255, 255, 255));
        tbContraseñaIngreso.setForeground(new java.awt.Color(51, 0, 153));
        tbContraseñaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbContraseñaIngresoActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login_BotonPassword_Normal.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login_BotonLogin_Normal.png"))); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login_BotonRegister_Normal.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login_BG.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout IngresarLayout = new javax.swing.GroupLayout(Ingresar);
        Ingresar.setLayout(IngresarLayout);
        IngresarLayout.setHorizontalGroup(
            IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tbEmailIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(IngresarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tbContraseñaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(IngresarLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButton5))
            .addGroup(IngresarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(IngresarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        IngresarLayout.setVerticalGroup(
            IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(tbEmailIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(tbContraseñaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton5)
                .addGap(32, 32, 32)
                .addComponent(btnIngresar)
                .addGap(0, 0, 0)
                .addComponent(jButton6))
            .addComponent(jLabel13)
        );

        PanelPrincipal.add(Ingresar, "Ingresar");

        resetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ForgotPasswrd_ResetPassword.png"))); // NOI18N
        resetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordActionPerformed(evt);
            }
        });

        ResetPasswrod_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        ResetPasswrod_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPasswrod_BackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ForgotPassw_BG-01.jpg"))); // NOI18N

        javax.swing.GroupLayout RecuperarContraseñaLayout = new javax.swing.GroupLayout(RecuperarContraseña);
        RecuperarContraseña.setLayout(RecuperarContraseñaLayout);
        RecuperarContraseñaLayout.setHorizontalGroup(
            RecuperarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecuperarContraseñaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tbCorreoRecuperarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(RecuperarContraseñaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ResetPasswrod_Back))
            .addGroup(RecuperarContraseñaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(resetPassword))
            .addComponent(jLabel2)
        );
        RecuperarContraseñaLayout.setVerticalGroup(
            RecuperarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecuperarContraseñaLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(tbCorreoRecuperarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(ResetPasswrod_Back))
            .addGroup(RecuperarContraseñaLayout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(resetPassword))
            .addComponent(jLabel2)
        );

        PanelPrincipal.add(RecuperarContraseña, "RecuperarContraseña");

        Registrar1.setMaximumSize(new java.awt.Dimension(375, 667));
        Registrar1.setMinimumSize(new java.awt.Dimension(375, 667));
        Registrar1.setOpaque(false);
        Registrar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Registrar1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 290, -1));
        Registrar1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, -1));

        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        Registrar1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 290, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Registrar1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_BotonRegister_Normal.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Registrar1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 210, -1));

        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoKeyTyped(evt);
            }
        });
        Registrar1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 290, -1));

        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });
        Registrar1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 290, -1));
        Registrar1.add(confirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 290, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_BG_4-01.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        Registrar1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        PanelPrincipal.add(Registrar1, "Registrar1");

        jLabel7.setText("Fecha nacimiento");

        jLabel9.setText("Dia");

        jLabel10.setText("Mes");

        jLabel11.setText("Año");

        jLabel12.setText("Genero");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton9.setText("Atras");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Finalizar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout Registrar2Layout = new javax.swing.GroupLayout(Registrar2);
        Registrar2.setLayout(Registrar2Layout);
        Registrar2Layout.setHorizontalGroup(
            Registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registrar2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(Registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Registrar2Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Registrar2Layout.createSequentialGroup()
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10))
                        .addComponent(jLabel12)
                        .addComponent(jLabel7)
                        .addGroup(Registrar2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(59, 59, 59)
                            .addComponent(jLabel10)
                            .addGap(55, 55, 55)
                            .addComponent(jLabel11))
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        Registrar2Layout.setVerticalGroup(
            Registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Registrar2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(Registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(Registrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(376, Short.MAX_VALUE))
        );

        PanelPrincipal.add(Registrar2, "Registrar2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbContraseñaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbContraseñaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbContraseñaIngresoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.cardLayout.show(this.PanelPrincipal, "RecuperarContraseña");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ResetPasswrod_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPasswrod_BackActionPerformed
        this.cardLayout.show(this.PanelPrincipal, "Ingresar");
    }//GEN-LAST:event_ResetPasswrod_BackActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.cardLayout.show(this.PanelPrincipal, "Ingresar");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(correo.getText().isEmpty() || password.getText().isEmpty() || Nombre.getText().isEmpty() || apellido.getText().isEmpty() || confirmarPassword.getText().isEmpty()|| cedula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
            if(password.getText().equals(confirmarPassword.getText())){

                Gson gson = new Gson();
                ClienteTCP client = new ClienteTCP();
                HashMap usuario = new HashMap();

                usuario.put("accion","crear usuario");
                usuario.put("email",correo.getText());
                usuario.put("contraseña",password.getText());
                usuario.put("genero","");
                usuario.put("nombre",Nombre.getText());
                usuario.put("apellidos",apellido.getText());
                usuario.put("celular","");
                usuario.put("cedula",cedula.getText());

                String payload = gson.toJson(usuario);
                String resultado = client.enviaServidor(payload);
                JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
                boolean exito =  jsonObject.get("exito").getAsBoolean();

                if(!exito){
                    JOptionPane.showMessageDialog(null, "No se ha creado el usuario.");
                } else {
                    JOptionPane.showMessageDialog(null, "Se ha creado el usuario");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El password y el confirmar password no son iguales");
            }
            //this.cardLayout.show(this.PanelPrincipal, "Registrar2");
        }    
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.cardLayout.show(this.PanelPrincipal, "Registrar1");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(tbEmailIngreso.getText().isEmpty() || tbContraseñaIngreso.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todas las casillas");
        }else{
            String email = this.tbEmailIngreso.getText();
            String contraseña = this.tbContraseñaIngreso.getText();
            
            Gson gson = new Gson();
            ClienteTCP client = new ClienteTCP();
            HashMap usuario = new HashMap();
            usuario.put("email",email);
            usuario.put("contraseña",contraseña);
            usuario.put("accion","autenticar usuario");   
            String payload = gson.toJson(usuario);
            String resultado = client.enviaServidor(payload);
            JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
            boolean exito =  jsonObject.get("exito").getAsBoolean();
            
            if(!exito){
                JOptionPane.showMessageDialog(null, "La combinacion usuario no es correcta o el usuario no existe.");
            } else {
                InterfazPrincipal app = new InterfazPrincipal();
                app.setEmail(email);
                this.setVisible(false);
                app.setVisible(true);              
            }
            
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void tbEmailIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbEmailIngresoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEmailIngresoKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       this.cardLayout.show(this.PanelPrincipal, "Registrar1");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void resetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordActionPerformed
        if(tbCorreoRecuperarContraseña.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese un correo valido");
        }else{
            Gson gson = new Gson();
            ClienteTCP client = new ClienteTCP();
            HashMap usuario = new HashMap();
            String email = tbCorreoRecuperarContraseña.getText();
            
            usuario.put("email",email);
            usuario.put("accion","recuperar contraseña");  
            String payload = gson.toJson(usuario);
            String resultado = client.enviaServidor(payload);
            JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
            boolean exito =  jsonObject.get("exito").getAsBoolean();

            if (exito){
                JOptionPane.showMessageDialog(null, "Se ha enviado un email para reestablecer la contraseña");
            } else {
                JOptionPane.showMessageDialog(null, "No se ha encontrado el correo electrónico");
            }
        }   
    }//GEN-LAST:event_resetPasswordActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_apellidoKeyTyped

    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_cedulaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ingresar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel RecuperarContraseña;
    private javax.swing.JPanel Registrar1;
    private javax.swing.JPanel Registrar2;
    private javax.swing.JButton ResetPasswrod_Back;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField confirmarPassword;
    private javax.swing.JTextField correo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField password;
    private javax.swing.JButton resetPassword;
    private javax.swing.JTextField tbContraseñaIngreso;
    private javax.swing.JTextField tbCorreoRecuperarContraseña;
    private javax.swing.JTextField tbEmailIngreso;
    // End of variables declaration//GEN-END:variables
}
