/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_concurrente;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose9
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    CardLayout bodyCardLayout;
    String email = "usuario@correo.com";
    DefaultTableModel tablaAlertas;
    DefaultTableModel tablaContactos;
    ArrayList <ContactoEmergencia> contactos = new ArrayList();
    String idContacto;
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    String panelRetornoFiltros;
    /**
     * Creates new form InferfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        tablaAlertas = (DefaultTableModel) this.tblAlertas.getModel();
        tablaContactos = (DefaultTableModel) this.tblContactos.getModel();
        this.setLocationRelativeTo(null);
        this.bodyCardLayout = (CardLayout)(this.Body.getLayout());
        PanicBot.setBackground(new Color(0,0,0,0));
        Maps1.setBackground(new Color(0,0,0,0));
        Alertas1.setBackground(new Color(0,0,0,0));      
        jButton6.setBackground(new Color(0,0,0,0));  
        jButton1.setBackground(new Color(0,0,0,0));  
        jButton7.setBackground(new Color(0,0,0,0));  
        jButton2.setBackground(new Color(0,0,0,0));  
        btnAgregarAlerta.setBackground(new Color(0,0,0,0));  
        jButton20.setBackground(new Color(0,0,0,0));  
        jButton21.setBackground(new Color(0,0,0,0));
        jButton22.setBackground(new Color(0,0,0,0));
        jButton23.setBackground(new Color(0,0,0,0));
        jButton24.setBackground(new Color(0,0,0,0));
        jButton25.setBackground(new Color(0,0,0,0));
        jButton26.setBackground(new Color(0,0,0,0));
        jButton27.setBackground(new Color(0,0,0,0));
        //AlertasFiltro_Boton.setBackground(new Color(0,0,0,0));
        FiltroBack_Boton.setBackground(new Color(0,0,0,0));
        AjustesFiltroSave_Boton.setBackground(new Color(0,0,0,0));
        jButton12.setBackground(new Color(0,0,0,0));
        jButton14.setBackground(new Color(0,0,0,0));
        jButton15.setBackground(new Color(0,0,0,0));
        jButton17.setBackground(new Color(0,0,0,0));
        jButton16.setBackground(new Color(0,0,0,0));
        ModContactosSafe_Bot.setBackground(new Color(0,0,0,0));
        ChangePassSave_Boton.setBackground(new Color(0,0,0,0));
        jButton3.setBackground(new Color(0,0,0,0));
        jButton4.setBackground(new Color(0,0,0,0));
        jButton5.setBackground(new Color(0,0,0,0));
        jButton8.setBackground(new Color(0,0,0,0));
        btnAgregarContacto.setBackground(new Color(0,0,0,0));
        jButton9.setBackground(new Color(0,0,0,0));
        jButton10.setBackground(new Color(0,0,0,0));        
        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Principal = new javax.swing.JPanel();
        Principal_mensaje_label = new javax.swing.JLabel();
        PanicBot = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Alertas1 = new javax.swing.JButton();
        Maps1 = new javax.swing.JButton();
        Start_BG = new javax.swing.JLabel();
        Altertas = new javax.swing.JPanel();
        cbTiposAlertas = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlertas = new javax.swing.JTable();
        btnAgregarAlerta = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        Mapa = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        MapaLabel = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Filtros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        AjustesFiltroSave_Boton = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        FiltroBack_Boton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        PanelOpciones = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        BACKGOURND = new javax.swing.JLabel();
        ContactosAgregar = new javax.swing.JPanel();
        tbNombreContacto = new javax.swing.JTextField();
        tbApellidosContactos = new javax.swing.JTextField();
        tbTelefonoContacto = new javax.swing.JTextField();
        tbEmailContacto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblContactos = new javax.swing.JTable();
        btnAgregarContacto = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Perfil = new javax.swing.JPanel();
        perfilNombre = new javax.swing.JTextField();
        perfilApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        CambiarContraseña = new javax.swing.JPanel();
        actualPasswrd = new javax.swing.JTextField();
        nuevoPass = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        ChangePassSave_Boton = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        AgregarAlerta = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        ContactosModificar = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        tbModificarContactoNombre = new javax.swing.JTextField();
        tbModificarContactoApellido = new javax.swing.JTextField();
        tbModificarContactoNumero = new javax.swing.JTextField();
        tbModificarContactoCorreo = new javax.swing.JTextField();
        ModContactosSafe_Bot = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Creditos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 667));
        setMinimumSize(new java.awt.Dimension(375, 667));
        setResizable(false);
        setSize(new java.awt.Dimension(375, 667));

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setLayout(new java.awt.CardLayout());

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setPreferredSize(new java.awt.Dimension(375, 667));
        Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Principal_mensaje_label.setBackground(new java.awt.Color(204, 204, 204));
        Principal.add(Principal_mensaje_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 310, 30));

        PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_PanicBoton_Normal.png"))); // NOI18N
        PanicBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanicBotActionPerformed(evt);
            }
        });
        Principal.add(PanicBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 360, 470));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        Principal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Settings.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Principal.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 50, 40));

        Alertas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Alerta.png"))); // NOI18N
        Alertas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alertas1ActionPerformed(evt);
            }
        });
        Principal.add(Alertas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        Maps1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Mapa.png"))); // NOI18N
        Maps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Maps1ActionPerformed(evt);
            }
        });
        Principal.add(Maps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Normal_Blue-01.jpg"))); // NOI18N
        Principal.add(Start_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        Body.add(Principal, "Principal");

        Altertas.setBackground(new java.awt.Color(255, 255, 255));
        Altertas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbTiposAlertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agresion", "Asalto", "Hurto", "Vandalismo", "Otro" }));
        Altertas.add(cbTiposAlertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 180, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_Settings.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Altertas.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 50, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Altertas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, -1));

        tblAlertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Lugar", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tblAlertas);

        Altertas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 342, 370));

        btnAgregarAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alerta_Agregar.png"))); // NOI18N
        btnAgregarAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlertaActionPerformed(evt);
            }
        });
        Altertas.add(btnAgregarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 180, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alertas_BG-01.jpg"))); // NOI18N
        Altertas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Altertas, "Alertas");

        jPanel7.setBackground(new java.awt.Color(0, 153, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MapaLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MapaLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel7.add(MapaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 530));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BG-01.jpg"))); // NOI18N
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout MapaLayout = new javax.swing.GroupLayout(Mapa);
        Mapa.setLayout(MapaLayout);
        MapaLayout.setHorizontalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MapaLayout.setVerticalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Body.add(Mapa, "Mapa");

        Filtros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        Filtros.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 165, 261, -1));
        Filtros.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 339, 261, -1));
        Filtros.add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 391, 261, -1));

        AjustesFiltroSave_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        AjustesFiltroSave_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjustesFiltroSave_BotonActionPerformed(evt);
            }
        });
        Filtros.add(AjustesFiltroSave_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 160, 47));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        Filtros.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        FiltroBack_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        FiltroBack_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroBack_BotonActionPerformed(evt);
            }
        });
        Filtros.add(FiltroBack_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 30, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Alertas_BG-01.jpg"))); // NOI18N
        Filtros.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Filtros, "Filtros");

        PanelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Perfil.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 176, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ContactosBoton.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OpcionesBoton.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 176, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EdotarPassword_Boton.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 176, -1));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        PanelOpciones.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        BACKGOURND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BG-01.jpg"))); // NOI18N
        PanelOpciones.add(BACKGOURND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(PanelOpciones, "PanelOpciones");

        ContactosAgregar.setBackground(new java.awt.Color(255, 255, 255));
        ContactosAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbNombreContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbNombreContactoKeyTyped(evt);
            }
        });
        ContactosAgregar.add(tbNombreContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 152, 140, -1));

        tbApellidosContactos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbApellidosContactosKeyTyped(evt);
            }
        });
        ContactosAgregar.add(tbApellidosContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 152, 140, -1));

        tbTelefonoContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbTelefonoContactoKeyTyped(evt);
            }
        });
        ContactosAgregar.add(tbTelefonoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 230, 320, -1));
        ContactosAgregar.add(tbEmailContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 300, 320, -1));

        tblContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Telefono", "Email"
            }
        ));
        jScrollPane3.setViewportView(tblContactos);

        ContactosAgregar.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 386, 330, 203));

        btnAgregarContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AgregarBoton.png"))); // NOI18N
        btnAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContactoActionPerformed(evt);
            }
        });
        ContactosAgregar.add(btnAgregarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 340, 150, 40));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModificarBoton.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        ContactosAgregar.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 150, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EliminarBoton.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        ContactosAgregar.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 160, -1));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        ContactosAgregar.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ContactosAgregar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AddContactBG-01.jpg"))); // NOI18N
        ContactosAgregar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(ContactosAgregar, "ContactosAgregar");

        Perfil.setBackground(new java.awt.Color(255, 255, 255));
        Perfil.setAutoscrolls(true);
        Perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perfilNombre.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                perfilNombreAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        perfilNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perfilNombreKeyTyped(evt);
            }
        });
        Perfil.add(perfilNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 290, -1));

        perfilApellido.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                perfilApellidoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        perfilApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perfilApellidoKeyTyped(evt);
            }
        });
        Perfil.add(perfilApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        Perfil.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        Perfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Perfil.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Perfil.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        Perfil.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BG-01.jpg"))); // NOI18N
        Perfil.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Perfil, "Perfil");

        CambiarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        CambiarContraseña.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CambiarContraseña.add(actualPasswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 202, 280, -1));
        CambiarContraseña.add(nuevoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, -1));
        CambiarContraseña.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 280, -1));

        ChangePassSave_Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        ChangePassSave_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassSave_BotonActionPerformed(evt);
            }
        });
        CambiarContraseña.add(ChangePassSave_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 160, -1));

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        CambiarContraseña.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        CambiarContraseña.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChangePasBG-01.jpg"))); // NOI18N
        CambiarContraseña.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(CambiarContraseña, "CambiarContraseña");

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarAlertaLayout = new javax.swing.GroupLayout(AgregarAlerta);
        AgregarAlerta.setLayout(AgregarAlertaLayout);
        AgregarAlertaLayout.setHorizontalGroup(
            AgregarAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlertaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton27)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        AgregarAlertaLayout.setVerticalGroup(
            AgregarAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAlertaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton27)
                .addContainerGap(573, Short.MAX_VALUE))
        );

        Body.add(AgregarAlerta, "AgregarAlerta");

        ContactosModificar.setBackground(new java.awt.Color(255, 255, 255));
        ContactosModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        ContactosModificar.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        tbModificarContactoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbModificarContactoNombreKeyTyped(evt);
            }
        });
        ContactosModificar.add(tbModificarContactoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 162, 310, -1));

        tbModificarContactoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbModificarContactoApellidoKeyTyped(evt);
            }
        });
        ContactosModificar.add(tbModificarContactoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 310, -1));

        tbModificarContactoNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbModificarContactoNumeroKeyTyped(evt);
            }
        });
        ContactosModificar.add(tbModificarContactoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 310, -1));
        ContactosModificar.add(tbModificarContactoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 310, -1));

        ModContactosSafe_Bot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SaveBoton.png"))); // NOI18N
        ModContactosSafe_Bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModContactosSafe_BotActionPerformed(evt);
            }
        });
        ContactosModificar.add(ModContactosSafe_Bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        ContactosModificar.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ModContacto-01.jpg"))); // NOI18N
        ContactosModificar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(ContactosModificar, "ContactosModificar");

        Creditos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Christian Harding");
        Creditos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Daniela Pacheco");
        Creditos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Jose Moya");
        Creditos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Head_Logo.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        Creditos.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Register_Back.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Creditos.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BG-01.jpg"))); // NOI18N
        BG.setText("Daniela Pacheco Theodoluz");
        Creditos.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Body.add(Creditos, "creditos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.bodyCardLayout.show(this.Body, "Perfil");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.refrescarTablaContactos();
        this.bodyCardLayout.show(this.Body, "ContactosAgregar");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.bodyCardLayout.show(this.Body, "CambiarContraseña");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int filaSeleccionada = tblContactos.getSelectedRow();
        if(filaSeleccionada>-1){
        String nombre = tablaContactos.getValueAt(filaSeleccionada, 0).toString();
        String apellidos = tablaContactos.getValueAt(filaSeleccionada, 1).toString();
        String telefono = tablaContactos.getValueAt(filaSeleccionada, 2).toString();
        String email = tablaContactos.getValueAt(filaSeleccionada, 3).toString();
        
        for (ContactoEmergencia contacto:contactos){
            if (contacto.getEmail().equals(email)){
                this.idContacto = contacto.getId();
            }
        }
        
        tbModificarContactoNombre.setText(nombre);
        tbModificarContactoApellido.setText(apellidos);
        tbModificarContactoCorreo.setText(email);
        tbModificarContactoNumero.setText(telefono);
        this.bodyCardLayout.show(this.Body, "ContactosModificar");
        
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione alguno de los contactos en la tabla.");
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void AjustesFiltroSave_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjustesFiltroSave_BotonActionPerformed

    }//GEN-LAST:event_AjustesFiltroSave_BotonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.bodyCardLayout.show(this.Body,"PanelOpciones");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Alertas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alertas1ActionPerformed
        this.refrescarTablaAlertas();
        this.bodyCardLayout.show(this.Body,"Alertas");
    }//GEN-LAST:event_Alertas1ActionPerformed

    private void Maps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Maps1ActionPerformed
        this.bodyCardLayout.show(this.Body,"Mapa");
    }//GEN-LAST:event_Maps1ActionPerformed

    private void PanicBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanicBotActionPerformed
        if(PanicBot.isSelected()){   
            PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonPanico_Rojo.png")));
            Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Alert_Red-01.jpg")));
            
            Gson gson = new Gson();
            ClienteTCP client = new ClienteTCP();
            HashMap usuario = new HashMap();
            
            usuario.put("email",email);
            usuario.put("accion","emergencia");  
            String payload = gson.toJson(usuario);
            String resultado = client.enviaServidor(payload);
            JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
            boolean exito =  jsonObject.get("exito").getAsBoolean();

            if (exito){
               Principal_mensaje_label.setText("Se han enviado alertas a sus contactos de emergencia");
            } else {
                Principal_mensaje_label.setText("No se ha encontrado ningun contacto de emergencia");
            }

        } else {
           PanicBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_PanicBoton_Normal.png")));
           Start_BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Start_BG_Normal_Blue-01.jpg"))); 
           Principal_mensaje_label.setText("");
        }
            
    }//GEN-LAST:event_PanicBotActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       this.bodyCardLayout.show(this.Body,"PanelOpciones");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAgregarAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlertaActionPerformed
//        this.bodyCardLayout.show(this.Body,"AgregarAlerta");
        String tipoAlerta = this.cbTiposAlertas.getSelectedItem().toString();
        Gson gson = new Gson();
        ClienteTCP client = new ClienteTCP();
        HashMap usuario = new HashMap();

        usuario.put("tipoAlerta",tipoAlerta);
        usuario.put("accion","crear alerta");  
        usuario.put("email",email);
        String payload = gson.toJson(usuario);
        String resultado = client.enviaServidor(payload);
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        boolean exito =  jsonObject.get("exito").getAsBoolean();
//        this.refrescarTablaAlertas();
        if (exito){
            JOptionPane.showMessageDialog(null, "Se ha enviado la alerta al servidor.");
            Date fecha = Calendar.getInstance().getTime();
            
            String [] row = {fecha.toString(),"San Jose",tipoAlerta};
            tablaAlertas.addRow(row);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha enviado la alerta al servidor.");
        }        
        
    }//GEN-LAST:event_btnAgregarAlertaActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        this.bodyCardLayout.show(this.Body,"Principal");
    }//GEN-LAST:event_jButton27ActionPerformed

    private void btnAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContactoActionPerformed
        if(tbNombreContacto.getText().isEmpty() || tbApellidosContactos.getText().isEmpty() || tbTelefonoContacto.getText().isEmpty() || tbEmailContacto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
        HashMap usuario = new HashMap();
        ClienteTCP client = new ClienteTCP();
        Gson gson = new Gson();
        
        usuario.put("accion","crear contacto de emergencia");
        usuario.put("id",email);
        usuario.put("email",tbEmailContacto.getText());
        usuario.put("nombre",tbNombreContacto.getText());
        usuario.put("apellidos",tbApellidosContactos.getText());
        usuario.put("celular",tbTelefonoContacto.getText());
        
        String payload = gson.toJson(usuario);
        String resultado = client.enviaServidor(payload);
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        boolean exito =  jsonObject.get("exito").getAsBoolean();

         if (exito){
            this.refrescarTablaContactos();
         } 

        }
        
    }//GEN-LAST:event_btnAgregarContactoActionPerformed

    private void ModContactosSafe_BotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModContactosSafe_BotActionPerformed
         if(tbModificarContactoNombre.getText().isEmpty() || tbModificarContactoApellido.getText().isEmpty() || tbModificarContactoCorreo.getText().isEmpty() || tbModificarContactoNumero.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
            HashMap usuario = new HashMap();
            ClienteTCP client = new ClienteTCP();
            Gson gson = new Gson();

            usuario.put("accion","modificar contacto de emergencia");
            usuario.put("id",this.idContacto);
            usuario.put("email",tbModificarContactoCorreo.getText());
            usuario.put("nombre",tbModificarContactoNombre.getText());
            usuario.put("apellidos",tbModificarContactoApellido.getText());
            usuario.put("celular",tbModificarContactoNumero.getText());

            String payload = gson.toJson(usuario);
            String resultado = client.enviaServidor(payload);
            JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
            boolean exito =  jsonObject.get("exito").getAsBoolean();

             if (exito){
                 this.refrescarTablaContactos();
                 JOptionPane.showMessageDialog(null, "Se modificaron los datos del contacto.");
             } else {
                 JOptionPane.showMessageDialog(null, "Error: No se modificaron los datos del contacto.");
             } 
            
        }
    }//GEN-LAST:event_ModContactosSafe_BotActionPerformed

    private void ChangePassSave_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassSave_BotonActionPerformed
        if(nuevoPass.getText().isEmpty() || jTextField16.getText().isEmpty() || actualPasswrd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else if(nuevoPass.getText().length() <6){
            JOptionPane.showMessageDialog(null, "Por favor ingrese una contrasena de mas de 6 digitos");
        }else if (!nuevoPass.getText().equals(jTextField16.getText())){
            JOptionPane.showMessageDialog(null, "Las contraseña no son iguales");
        }else {
            if(nuevoPass.getText().equals(jTextField16.getText())){
                
                Gson gson = new Gson();
                ClienteTCP client = new ClienteTCP();
                HashMap usuario = new HashMap();
                
                usuario.put("email",this.email);
                usuario.put("contrasena actual", actualPasswrd.getText());                
                usuario.put("nueva contrasena",nuevoPass.getText());
                usuario.put("accion","cambiar contraseña");
                String payload =gson.toJson(usuario);
                String resultado = client.enviaServidor(payload);
                JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
                boolean exito =  jsonObject.get("exito").getAsBoolean();
                
                 if (exito){
                     JOptionPane.showMessageDialog(null, "Se cambio la contraseña");
                 }
            
            }
            
        }
    }//GEN-LAST:event_ChangePassSave_BotonActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(perfilNombre.getText().isEmpty() || perfilApellido.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
        }else{
                Gson gson = new Gson();
                ClienteTCP client = new ClienteTCP();
                HashMap usuario = new HashMap();
                
                usuario.put("email",this.email);
                usuario.put("nombre", perfilNombre.getText());                
                usuario.put("apellidos",perfilApellido.getText());
                usuario.put("accion","modificar mis datos");
                String payload =gson.toJson(usuario);
                String resultado = client.enviaServidor(payload);
                JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
                boolean exito =  jsonObject.get("exito").getAsBoolean();
                
                 if (exito){
                     JOptionPane.showMessageDialog(null, "Se cambio la contraseña");
                 }            
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void FiltroBack_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroBack_BotonActionPerformed
        this.bodyCardLayout.show(this.Body, "Alertas");
    }//GEN-LAST:event_FiltroBack_BotonActionPerformed

    private void tbNombreContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNombreContactoKeyTyped
       char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_tbNombreContactoKeyTyped

    private void tbApellidosContactosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbApellidosContactosKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_tbApellidosContactosKeyTyped

    private void tbTelefonoContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbTelefonoContactoKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_tbTelefonoContactoKeyTyped

    private void perfilNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perfilNombreKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_perfilNombreKeyTyped

    private void perfilApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perfilApellidoKeyTyped
char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_perfilApellidoKeyTyped

    private void tbModificarContactoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbModificarContactoNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_tbModificarContactoNombreKeyTyped

    private void tbModificarContactoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbModificarContactoApellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_tbModificarContactoApellidoKeyTyped

    private void tbModificarContactoNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbModificarContactoNumeroKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_SHIFT)){
            evt.consume();
        }
    }//GEN-LAST:event_tbModificarContactoNumeroKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.bodyCardLayout.show(this.Body, "PanelOpciones");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.bodyCardLayout.show(this.Body, "PanelOpciones");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.bodyCardLayout.show(this.Body, "PanelOpciones");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.bodyCardLayout.show(this.Body, "ContactosAgregar");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void perfilNombreAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_perfilNombreAncestorAdded
        Gson gson = new Gson();
        ClienteTCP client = new ClienteTCP();
        HashMap usuario = new HashMap();
        
        usuario.put("email",this.email);
        usuario.put("accion", "mis datos");
        String payload = gson.toJson(usuario);//Serializa parametros en formato JSON
        String resultado= client.enviaServidor(payload); //Agrega el mensaje devuelto por el servidor a un string
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        System.out.println(jsonObject.toString());
        String stringTemporal = jsonObject.get("reporte").getAsString();
        jsonObject = new JsonParser().parse(stringTemporal).getAsJsonObject();
        String nombre = jsonObject.get("nombre").getAsString();
        perfilNombre.setText(nombre);

        

    }//GEN-LAST:event_perfilNombreAncestorAdded

    private void perfilApellidoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_perfilApellidoAncestorAdded
        Gson gson = new Gson();
        ClienteTCP client = new ClienteTCP();
        HashMap usuario = new HashMap();
        
        usuario.put("email",this.email);
        usuario.put("accion", "mis datos");
        String payload = gson.toJson(usuario);//Serializa parametros en formato JSON
        String resultado= client.enviaServidor(payload); //Agrega el mensaje devuelto por el servidor a un string
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        System.out.println(jsonObject.toString());
        String stringTemporal = jsonObject.get("reporte").getAsString();
        jsonObject = new JsonParser().parse(stringTemporal).getAsJsonObject();
        String nombre = jsonObject.get("apellidos").getAsString();
        perfilApellido.setText(nombre);
    }//GEN-LAST:event_perfilApellidoAncestorAdded

    private void MapaLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MapaLabelAncestorAdded
  //        String marker = null;
//        String latitud = "9.941295";
//        String longitud = "-84.079674";
//        marker += "&markers="+latitud+"%2C+"+longitud; 
//        String startURL = "http://maps.googleapis.com/maps/api/staticmap?center=9.9360505%2C+-84.0790755&zoom=16&size=300x650&scale=1&format=png&maptype=terrain";
//        String endURL = "&region=es&language=es&sensor=false&key=AIzaSyAWZLD2A6ltEb4HMzzRgNbOEgLJ1Sm89KI=";
          ClienteUDP udp = new ClienteUDP();
          String msg = udp.enviaServidor();
          System.out.println(msg);
        try {
            //
            URL url = new URL(msg);
            BufferedImage image = ImageIO.read(url);
            MapaLabel.setIcon(new javax.swing.ImageIcon(image));
//        try {
//            url = new URL(msg);
//        } catch (MalformedURLException ex) {
//            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            image = ImageIO.read(url);
//        } catch (IOException ex) {
//            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        System.out.println(image);
//        MapaLabel.setIcon(new javax.swing.ImageIcon(image));
        } catch (MalformedURLException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MapaLabelAncestorAdded

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int filaSeleccionada = tblContactos.getSelectedRow();
        if(filaSeleccionada>-1){
        String nombre = tablaContactos.getValueAt(filaSeleccionada, 0).toString();
        String apellidos = tablaContactos.getValueAt(filaSeleccionada, 1).toString();
        String telefono = tablaContactos.getValueAt(filaSeleccionada, 2).toString();
        String email = tablaContactos.getValueAt(filaSeleccionada, 3).toString();
        this.idContacto="";
        for (ContactoEmergencia contacto:contactos){
            if (contacto.getEmail().equals(email)){
                this.idContacto = contacto.getId();
            }
        }
        Gson gson = new Gson(); //Objeto gson para serializar String a formato Json
        ClienteTCP client = new ClienteTCP(); //Cliente TCP para enviar datos
        HashMap reporte = new HashMap(); //Hashmap para enviar parametros al servidor
        JsonArray output = null; //Crea objeto nuevo de tipo JsonArray para poder acceder a cada evento individualmente
        
        //Agrega parametros
        reporte.put("accion","eliminar contacto de emergencia");  
        reporte.put("id",this.idContacto);
        
        String payload = gson.toJson(reporte);//Serializa parametros en formato JSON
        String resultado = client.enviaServidor(payload); //Agrega el mensaje devuelto por el servidor a un string
        refrescarTablaContactos();
        
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione alguno de los contactos en la tabla.");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       this.bodyCardLayout.show(this.Body, "creditos");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        this.bodyCardLayout.show(this.Body, "Principal");
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.bodyCardLayout.show(this.Body, "PanelOpciones");
    }//GEN-LAST:event_jButton11ActionPerformed

    private JsonArray extraerAlertas(){
        Gson gson = new Gson(); //Objeto gson para serializar String a formato Json
        ClienteTCP client = new ClienteTCP(); //Cliente TCP para enviar datos
        HashMap reporte = new HashMap(); //Hashmap para enviar parametros al servidor
        JsonArray output = null; //Crea objeto nuevo de tipo JsonArray para poder acceder a cada evento individualmente
        
        //Agrega parametros
        reporte.put("accion","mis alertas");  
        reporte.put("email",email);
        
        String payload = gson.toJson(reporte);//Serializa parametros en formato JSON
        String resultado = client.enviaServidor(payload); //Agrega el mensaje devuelto por el servidor a un string

        //Se deserializa el string para extraer los eventos
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        String stringTemporal = jsonObject.get("reporte").getAsString();
//        System.out.println(prueba);

        if (!stringTemporal.equals("")){
        jsonObject = new JsonParser().parse(stringTemporal).getAsJsonObject();
        stringTemporal = jsonObject.get("eventos").getAsString();
    //        System.out.println(prueba);
        output = new JsonParser().parse(stringTemporal).getAsJsonArray();
    //        System.out.println(aux.toString());        
        }
        return output;
    }
    
    private void refrescarTablaAlertas(){
        JsonArray aux = this.extraerAlertas();
        JsonObject jsonObject;
        //Se itera en cada item del array para agregar una linea nueva a la tabla
        if (aux!=null){
            tablaAlertas.setNumRows(0);
            for (int i = 0; i < aux.size(); i++) {
                jsonObject = aux.get(i).getAsJsonObject();
                //Se extraen elementos especificos y se agregan a un array string
                String fecha = jsonObject.get("fecha").getAsString();
                String tipo = jsonObject.get("tipoAlerta").getAsString();
                String lugar = jsonObject.get("barrio").getAsString();
                String [] row = {fecha.toString(),lugar,tipo};
                tablaAlertas.addRow(row);
            }
        }
    }
    
    private void refrescarTablaContactos(){
        JsonArray arrayContactos = this.extraerContactos();
        tablaContactos.setRowCount(0);
        if (arrayContactos!=null){
            
            for (int i = 0; i < arrayContactos.size(); i++) {
                JsonObject jsonObject = arrayContactos.get(i).getAsJsonObject();
                //Se extraen elementos especificos y se agregan a un array string
                String nombre = jsonObject.get("nombre").getAsString();
                String apellidos = jsonObject.get("apellidos").getAsString();
                String celular = jsonObject.get("celular").getAsString();
                String email = jsonObject.get("email").getAsString();
                String id = jsonObject.get("id").getAsString();
                String [] row = {nombre, apellidos, celular,email};
                tablaContactos.addRow(row);
                ContactoEmergencia c = new ContactoEmergencia(this.email, id, email, nombre, apellidos, celular);
                contactos.add(c);
            }  
        }
        
    }
    
    private JsonArray extraerContactos(){
        Gson gson = new Gson();
        ClienteTCP client = new ClienteTCP();
        HashMap usuario = new HashMap();
        JsonArray arrayContactos = null;

        usuario.put("email",email);
        usuario.put("accion","mis contactos");  
        String payload = gson.toJson(usuario);
        String resultado = client.enviaServidor(payload);
        JsonObject jsonObject = new JsonParser().parse(resultado).getAsJsonObject();
        boolean exito =  jsonObject.get("exito").getAsBoolean();

        String stringTemporal = jsonObject.get("reporte").getAsString();
        if (!stringTemporal.equals("")){
            jsonObject = new JsonParser().parse(stringTemporal).getAsJsonObject();
            stringTemporal = jsonObject.get("contactos").getAsString();
            arrayContactos = new JsonParser().parse(stringTemporal).getAsJsonArray();

        }
        
        return arrayContactos;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarAlerta;
    private javax.swing.JButton AjustesFiltroSave_Boton;
    private javax.swing.JButton Alertas1;
    private javax.swing.JPanel Altertas;
    private javax.swing.JLabel BACKGOURND;
    private javax.swing.JLabel BG;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel CambiarContraseña;
    private javax.swing.JButton ChangePassSave_Boton;
    private javax.swing.JPanel ContactosAgregar;
    private javax.swing.JPanel ContactosModificar;
    private javax.swing.JPanel Creditos;
    private javax.swing.JButton FiltroBack_Boton;
    private javax.swing.JPanel Filtros;
    private javax.swing.JPanel Mapa;
    private javax.swing.JLabel MapaLabel;
    private javax.swing.JButton Maps1;
    private javax.swing.JButton ModContactosSafe_Bot;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JToggleButton PanicBot;
    private javax.swing.JPanel Perfil;
    private javax.swing.JPanel Principal;
    private javax.swing.JLabel Principal_mensaje_label;
    private javax.swing.JLabel Start_BG;
    private javax.swing.JTextField actualPasswrd;
    private javax.swing.JButton btnAgregarAlerta;
    private javax.swing.JButton btnAgregarContacto;
    private javax.swing.JComboBox<String> cbTiposAlertas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField nuevoPass;
    private javax.swing.JTextField perfilApellido;
    private javax.swing.JTextField perfilNombre;
    private javax.swing.JTextField tbApellidosContactos;
    private javax.swing.JTextField tbEmailContacto;
    private javax.swing.JTextField tbModificarContactoApellido;
    private javax.swing.JTextField tbModificarContactoCorreo;
    private javax.swing.JTextField tbModificarContactoNombre;
    private javax.swing.JTextField tbModificarContactoNumero;
    private javax.swing.JTextField tbNombreContacto;
    private javax.swing.JTextField tbTelefonoContacto;
    private javax.swing.JTable tblAlertas;
    private javax.swing.JTable tblContactos;
    // End of variables declaration//GEN-END:variables
}
